config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get '/', to: 'home#index', as: 'home'

  resources :gossips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :gossips
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:anonymous_username])
  end
  
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossip = Gossip.new
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def create
    gossip = Gossip.new
    gossip.user = current_user
    gossip.content = params[:gossip][:content]
    gossip.save
    flash[:notice] = "Gossip Completed"
    redirect_to home_path
  end

  def destroy
    gossip = Gossip.find(params[:id])
    gossip.destroy
    redirect_to home_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossips = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gossips/new.html.erb
<h1>Création d'un gossip</h1>

<p>Entre tes infos</p><br>

<%= form_for @gossip do |f| %>

  <%= label_tag 'Que sais-tu ?' %>
  <%= f.text_field :content, placeholder: "blablabla" %><br>

  <%= f.submit "Valide ton gossip !" %>

<% end %>

<p><a href="<%= home_path %>"><button type="button" name="button">Revenir à la page d'accueil</button></a></p>

app/views/home/index.html.erb
<h1>THP ANONYMOUS GOSSIP PROJECT</h1>


<% if user_signed_in? %>

  <h3>Bonjour à toi, <%= current_user.anonymous_username %> !<br> Bienvenue sur le meilleur forum de commérage au monnnnnde !</h1>

  <p><b>Sans plus attendre, je te présente la liste des potins du moment :</b><br><br>

    <div class=row>
      <% @gossips.each do |gossip| %>

        <div class="card col-lg-2 col-sm-4" >
          <div class="card-body">
            <div style="display: flex">
              <h5 class="card-title">
                Gossip numéro : <%= gossip.id %>
              </h5>
            </div>
            <h6 class="card-subtitle mb-2 text-muted"> <strong>Auteur</strong> : <%=gossip.user.anonymous_username%></h6>
            <p class="card-text" > <strong>Contenu</strong>: <%= gossip.content %> </p>
          </div>
          <div class="row">
            <div class="col-6">
              <%= link_to 'Détails', gossip_path(gossip.id), class:"btn btn-link" %>
            </div>
            <div class="col-6">
              <% if current_user == gossip.user %>
                <%= link_to "Destroy gossip", gossip_path(gossip), method: :delete, class:"btn btn-link" %>
              <%end%>
            </div>
          </div>
      </div>
      <% end %>
    </div>

<% else %>

  <p>Hey, log in or sign in !</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>DeviseTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="nav">

          <li class="nav-item">
            <a class="nav-link active" href="<%= home_path %>">Home</a>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_gossip_path %>">Create gossip</a>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li>
              <a class="nav-link" href="<%= edit_user_registration_path %>">Edit account</a>
            </li>


          <% else %>
            <li class="nav-item">
              <a class="nav-link active" href="<%= new_user_session_path %>">Connexion</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="<%= new_user_registration_path %>">Nouveau compte</a>
            </li>

        <% end %>
      </ul>
    </nav>


  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>